driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
    run_list: apt::default
  - name: debian-9
    run_list: apt::default
  - name: freebsd-10
  - name: freebsd-11
  - name: fedora-28
  - name: opensuse-leap-42
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: macos-10.12
    run_list: homebrew::default
    driver:
      box: chef/macos-10.12 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
  - name: default
    run_list: openssh::default
  - name: iptables
    run_list: openssh::iptables
    excludes:
      - macosx-10.11
